---

image: registry.gitlab.com/vpnbeast/docker-images/docker-base:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - release

test_merge_request:
  stage: test
  before_script:
    - chmod +x ci-scripts/test.sh
  script:
    - /bin/sh ci-scripts/test.sh
  rules:
    - if: $CI_MERGE_REQUEST_ID

test:
  stage: test
  before_script:
    - chmod +x ci-scripts/test.sh
  script:
    - /bin/sh ci-scripts/test.sh
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch

release:
  stage: release
  before_script:
    - chmod +x ci-scripts/release.sh
  script:
    - /bin/sh ci-scripts/release.sh master
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
