{{- if .Values.ingress.enabled -}}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  {{- if .Values.ingress.rules }}
  rules:
  {{- toYaml .Values.ingress.rules | nindent 4 }}
  {{- end }}

{{- end }}
