{{- if .Values.ingress.enabled -}}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /vpnbeast-service(/|$)(.*)
        backend:
          serviceName: {{ .Values.deployment.name | quote }}
          servicePort: {{ .Values.deployment.serverPort }}

{{- end }}
