{{- if .Values.gateway.enabled -}}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vpnbeast-service
spec:
  hosts:
  - api.thevpnbeast.com
  gateways:
  - 'istio-system/istio-ingressgateway'
  {{- if .Values.gateway.routes }}
  http:
  {{- toYaml .Values.gateway.routes | nindent 2 }}
  {{- end }}

{{- end }}
