---

# https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

name: PR
on:
  pull_request:

jobs:
  mvn_verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
      - name: Run the Maven test phase
        env:
          SPRING_PROFILES_ACTIVE: unit-test
        run: mvn clean verify
